Update config.py
Deletes an error:
Traceback (most recent call last):
  File "C:\Users\peter.jung\Desktop\20221219_GemAct-Umsetzung bzw. Pricing.py", line 29, in <module>
    layers = gem.LayerTower(au_ah_layer_1, au_ah_layer_2, ah_top_layer)
  File "C:\Users\peter.jung\AppData\Roaming\Python\Python311\site-packages\gemact\lossmodel.py", line 281, in __init__
    self.deductible_type = 'non-ranking eel' if deductible_type is None else deductible_type
  File "C:\Users\peter.jung\AppData\Roaming\Python\Python311\site-packages\gemact\lossmodel.py", line 309, in deductible_type
    hf.assert_member(value, config.DEDUCTIBLE_TYPE, logger)
AttributeError: module 'gemact.config' has no attribute 'DEDUCTIBLE_TYPE'


Do these two types suffice as deductible_type or is another type needed additionally? (e.g. is somewhere None a default value, which wouldn't be an instance of these two types.)